{% set python_min = "3.10" %}
{% set name = "dbt-ibis" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_ibis-{{ version }}.tar.gz
  sha256: ae175dd5b8fc2f8a7611222a4f619b97858da26aaf7b3c3be544f9152b39bc57

build:
  entry_points:
    - dbt-ibis = dbt_ibis:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - dbt-core >=1.5
    - ibis-framework >=9
    - click

test:
  imports:
    - dbt_ibis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Write your dbt models using Ibis
  home: https://github.com/binste/dbt-ibis
  dev_url: https://github.com/binste/dbt-ibis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - binste
