{% set name = "dbt-ibis" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt_ibis-{{ version }}.tar.gz
  sha256: cada5468cefac58f276d045b417f10d76f2e088d1c21a46a7d3c9c1767d4ee4a

build:
  entry_points:
    - dbt-ibis = dbt_ibis:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - dbt-core >=1.5
    - ibis-framework >=7
    - click

test:
  imports:
    - dbt_ibis
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Write your dbt models using Ibis
  home: https://github.com/binste/dbt-ibis
  dev_url: https://github.com/binste/dbt-ibis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - binste
